<?php
/**
 * Channels
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Scloby Api
 *
 * <a href='https://developer.scloby.com/apidoc/assets/documentation.json' target='_blank'>https://developer.scloby.com/apidoc/assets/documentation.json</a>  **Introduction**  **The authentication token is issued via Oauth2 standard ( https://oauth.net)**    You can apply for a Scloby test account on our developer portal **https://developer.scloby.com**   Here is your **ClientId** and **ClientSecret** for tests:    **client_id**: SclobyApiDocs    **client_secret**: DdyPNPvfPOGa0Izjct0C   **All data is JSON format, and the Content-Type header of POST/PUT request must be set to application/json.**  **Search Parameters**  You can perform a search in a collection using all first level properties in combination with some parameter, or specifying a value:    property = VALUE if you are searching for all items with a specific property value    property_since = MIN_VALUE if you are searching for all items with property value greater (or equal) than MIN_VALUE     property_max   = MAX_VALUE if you are searching for all items with property value smaller (or equal)than MAX_VALUE   property_like  = LIKE_VALUE if you are searching for a substring content.   You can use property_since and property_max in order to simulate **between** operator If you are using *equal* operator, all other operators for that parameter *will be ingnored*   If you are using _max or _since operator in strings, the alphabetical ordering will be used
 *
 * OpenAPI spec version: 2.0.0
 * Contact: dev@scloby.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Channels Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Channels implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'channels';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
'name' => 'string',
'image_url' => 'string',
'url' => 'string',
'enabled' => 'bool',
'allow_automatic_print' => 'bool',
'force_paid' => 'bool',
'add_to_mail_receipts' => 'bool',
'add_to_new_items' => 'bool',
'default_payment_method_id' => 'int'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
'name' => null,
'image_url' => null,
'url' => null,
'enabled' => null,
'allow_automatic_print' => null,
'force_paid' => null,
'add_to_mail_receipts' => null,
'add_to_new_items' => null,
'default_payment_method_id' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
'name' => 'name',
'image_url' => 'image_url',
'url' => 'url',
'enabled' => 'enabled',
'allow_automatic_print' => 'allow_automatic_print',
'force_paid' => 'force_paid',
'add_to_mail_receipts' => 'add_to_mail_receipts',
'add_to_new_items' => 'add_to_new_items',
'default_payment_method_id' => 'default_payment_method_id'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
'name' => 'setName',
'image_url' => 'setImageUrl',
'url' => 'setUrl',
'enabled' => 'setEnabled',
'allow_automatic_print' => 'setAllowAutomaticPrint',
'force_paid' => 'setForcePaid',
'add_to_mail_receipts' => 'setAddToMailReceipts',
'add_to_new_items' => 'setAddToNewItems',
'default_payment_method_id' => 'setDefaultPaymentMethodId'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
'name' => 'getName',
'image_url' => 'getImageUrl',
'url' => 'getUrl',
'enabled' => 'getEnabled',
'allow_automatic_print' => 'getAllowAutomaticPrint',
'force_paid' => 'getForcePaid',
'add_to_mail_receipts' => 'getAddToMailReceipts',
'add_to_new_items' => 'getAddToNewItems',
'default_payment_method_id' => 'getDefaultPaymentMethodId'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['image_url'] = isset($data['image_url']) ? $data['image_url'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['enabled'] = isset($data['enabled']) ? $data['enabled'] : null;
        $this->container['allow_automatic_print'] = isset($data['allow_automatic_print']) ? $data['allow_automatic_print'] : null;
        $this->container['force_paid'] = isset($data['force_paid']) ? $data['force_paid'] : null;
        $this->container['add_to_mail_receipts'] = isset($data['add_to_mail_receipts']) ? $data['add_to_mail_receipts'] : null;
        $this->container['add_to_new_items'] = isset($data['add_to_new_items']) ? $data['add_to_new_items'] : null;
        $this->container['default_payment_method_id'] = isset($data['default_payment_method_id']) ? $data['default_payment_method_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets image_url
     *
     * @return string
     */
    public function getImageUrl()
    {
        return $this->container['image_url'];
    }

    /**
     * Sets image_url
     *
     * @param string $image_url image_url
     *
     * @return $this
     */
    public function setImageUrl($image_url)
    {
        $this->container['image_url'] = $image_url;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets enabled
     *
     * @return bool
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param bool $enabled enabled
     *
     * @return $this
     */
    public function setEnabled($enabled)
    {
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets allow_automatic_print
     *
     * @return bool
     */
    public function getAllowAutomaticPrint()
    {
        return $this->container['allow_automatic_print'];
    }

    /**
     * Sets allow_automatic_print
     *
     * @param bool $allow_automatic_print allow_automatic_print
     *
     * @return $this
     */
    public function setAllowAutomaticPrint($allow_automatic_print)
    {
        $this->container['allow_automatic_print'] = $allow_automatic_print;

        return $this;
    }

    /**
     * Gets force_paid
     *
     * @return bool
     */
    public function getForcePaid()
    {
        return $this->container['force_paid'];
    }

    /**
     * Sets force_paid
     *
     * @param bool $force_paid force_paid
     *
     * @return $this
     */
    public function setForcePaid($force_paid)
    {
        $this->container['force_paid'] = $force_paid;

        return $this;
    }

    /**
     * Gets add_to_mail_receipts
     *
     * @return bool
     */
    public function getAddToMailReceipts()
    {
        return $this->container['add_to_mail_receipts'];
    }

    /**
     * Sets add_to_mail_receipts
     *
     * @param bool $add_to_mail_receipts add_to_mail_receipts
     *
     * @return $this
     */
    public function setAddToMailReceipts($add_to_mail_receipts)
    {
        $this->container['add_to_mail_receipts'] = $add_to_mail_receipts;

        return $this;
    }

    /**
     * Gets add_to_new_items
     *
     * @return bool
     */
    public function getAddToNewItems()
    {
        return $this->container['add_to_new_items'];
    }

    /**
     * Sets add_to_new_items
     *
     * @param bool $add_to_new_items add_to_new_items
     *
     * @return $this
     */
    public function setAddToNewItems($add_to_new_items)
    {
        $this->container['add_to_new_items'] = $add_to_new_items;

        return $this;
    }

    /**
     * Gets default_payment_method_id
     *
     * @return int
     */
    public function getDefaultPaymentMethodId()
    {
        return $this->container['default_payment_method_id'];
    }

    /**
     * Sets default_payment_method_id
     *
     * @param int $default_payment_method_id default_payment_method_id
     *
     * @return $this
     */
    public function setDefaultPaymentMethodId($default_payment_method_id)
    {
        $this->container['default_payment_method_id'] = $default_payment_method_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
