<?php
/**
 * OrdercustomerSchemaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Scloby Api
 *
 * <a href='https://developer.scloby.com/apidoc/assets/documentation.json' target='_blank'>https://developer.scloby.com/apidoc/assets/documentation.json</a>  **Introduction**  **The authentication token is issued via Oauth2 standard ( https://oauth.net)**    You can apply for a Scloby test account on our developer portal **https://developer.scloby.com**   Here is your **ClientId** and **ClientSecret** for tests:    **client_id**: SclobyApiDocs    **client_secret**: DdyPNPvfPOGa0Izjct0C   **All data is JSON format, and the Content-Type header of POST/PUT request must be set to application/json.**  **Search Parameters**  You can perform a search in a collection using all first level properties in combination with some parameter, or specifying a value:    property = VALUE if you are searching for all items with a specific property value    property_since = MIN_VALUE if you are searching for all items with property value greater (or equal) than MIN_VALUE     property_max   = MAX_VALUE if you are searching for all items with property value smaller (or equal)than MAX_VALUE   property_like  = LIKE_VALUE if you are searching for a substring content.   You can use property_since and property_max in order to simulate **between** operator If you are using *equal* operator, all other operators for that parameter *will be ingnored*   If you are using _max or _since operator in strings, the alphabetical ordering will be used
 *
 * OpenAPI spec version: 2.0.0
 * Contact: dev@scloby.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrdercustomerSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description OrdercustomerSchema
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrdercustomerSchemaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrdercustomerSchema"
     */
    public function testOrdercustomerSchema()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "custom_type"
     */
    public function testPropertyCustomType()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "birthdate"
     */
    public function testPropertyBirthdate()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "billing_street"
     */
    public function testPropertyBillingStreet()
    {
    }

    /**
     * Test attribute "billing_number"
     */
    public function testPropertyBillingNumber()
    {
    }

    /**
     * Test attribute "billing_city"
     */
    public function testPropertyBillingCity()
    {
    }

    /**
     * Test attribute "billing_zip"
     */
    public function testPropertyBillingZip()
    {
    }

    /**
     * Test attribute "billing_prov"
     */
    public function testPropertyBillingProv()
    {
    }

    /**
     * Test attribute "billing_country"
     */
    public function testPropertyBillingCountry()
    {
    }

    /**
     * Test attribute "shipping_street"
     */
    public function testPropertyShippingStreet()
    {
    }

    /**
     * Test attribute "shipping_number"
     */
    public function testPropertyShippingNumber()
    {
    }

    /**
     * Test attribute "shipping_city"
     */
    public function testPropertyShippingCity()
    {
    }

    /**
     * Test attribute "shipping_zip"
     */
    public function testPropertyShippingZip()
    {
    }

    /**
     * Test attribute "shipping_prov"
     */
    public function testPropertyShippingProv()
    {
    }

    /**
     * Test attribute "shipping_country"
     */
    public function testPropertyShippingCountry()
    {
    }

    /**
     * Test attribute "shipping_address_id"
     */
    public function testPropertyShippingAddressId()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "mobile"
     */
    public function testPropertyMobile()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "email_pec"
     */
    public function testPropertyEmailPec()
    {
    }

    /**
     * Test attribute "tax_code"
     */
    public function testPropertyTaxCode()
    {
    }

    /**
     * Test attribute "vat_code"
     */
    public function testPropertyVatCode()
    {
    }

    /**
     * Test attribute "sdi_code"
     */
    public function testPropertySdiCode()
    {
    }

    /**
     * Test attribute "fidelity"
     */
    public function testPropertyFidelity()
    {
    }

    /**
     * Test attribute "discount_perc"
     */
    public function testPropertyDiscountPerc()
    {
    }

    /**
     * Test attribute "sclobypass_id"
     */
    public function testPropertySclobypassId()
    {
    }

    /**
     * Test attribute "source_channel"
     */
    public function testPropertySourceChannel()
    {
    }

    /**
     * Test attribute "source_store"
     */
    public function testPropertySourceStore()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "payments_allowed"
     */
    public function testPropertyPaymentsAllowed()
    {
    }

    /**
     * Test attribute "payment_token"
     */
    public function testPropertyPaymentToken()
    {
    }

    /**
     * Test attribute "default_pricelist"
     */
    public function testPropertyDefaultPricelist()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "custom_1"
     */
    public function testPropertyCustom1()
    {
    }

    /**
     * Test attribute "custom_2"
     */
    public function testPropertyCustom2()
    {
    }

    /**
     * Test attribute "custom_3"
     */
    public function testPropertyCustom3()
    {
    }

    /**
     * Test attribute "custom_4"
     */
    public function testPropertyCustom4()
    {
    }

    /**
     * Test attribute "custom_5"
     */
    public function testPropertyCustom5()
    {
    }

    /**
     * Test attribute "custom_6"
     */
    public function testPropertyCustom6()
    {
    }

    /**
     * Test attribute "custom_7"
     */
    public function testPropertyCustom7()
    {
    }

    /**
     * Test attribute "custom_8"
     */
    public function testPropertyCustom8()
    {
    }

    /**
     * Test attribute "custom_9"
     */
    public function testPropertyCustom9()
    {
    }

    /**
     * Test attribute "facebook"
     */
    public function testPropertyFacebook()
    {
    }

    /**
     * Test attribute "twitter"
     */
    public function testPropertyTwitter()
    {
    }

    /**
     * Test attribute "linkedin"
     */
    public function testPropertyLinkedin()
    {
    }

    /**
     * Test attribute "instagram"
     */
    public function testPropertyInstagram()
    {
    }

    /**
     * Test attribute "disable_mail_receipts"
     */
    public function testPropertyDisableMailReceipts()
    {
    }
}
